### Create Admin User
POST http://localhost:3002/api/admin/sadmin/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWY0OWNjNmUxNTk0ZDI4MTc2ZDVhZTIiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtMjk0OCIsImlhdCI6MTcxMDUyOTczNCwiZXhwIjoxNzEwNTMzMzM0fQ.UETZoJ0hcGSfjakZ-bt-WBVf1ZbvEi69yGC8hh326aI
content-type: application/json

{
  "phoneNumber": "437-556-4035",
  "email": "svijayr007@gmail.com",
  "firstName": "Vijay",
  "lastName": "Pablo"
}

### New Admin Setup
POST http://localhost:3002/api/admin/setup
content-type: application/json

{
  "phoneNumber": "437-556-4035",
  "email": "svijayr007@gmail.com",
  "oneTimePassword": "vxmvq",
  "password": "Vijay@001"
}


### Admin Login
POST http://localhost:3002/api/admin/login
content-type: application/json

{
  "email": "svijayr007@gmail.com",
  "password": "Vijay@001"
}

### Admin Get All Users
GET http://localhost:3002/api/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWY0OWNmODIyZjFhOGY5M2RlYmZlNzgiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtNDAzNSIsImlhdCI6MTcxMDUyOTg1MSwiZXhwIjoxNzEwNjE2MjUxfQ.n5sc-ICMOjpyHadf5HSHRsVi7QvvSC_4j9hnu5oB07M
content-type: application/json