### Create Admin User
POST http://localhost:3002/api/admin/sadmin/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWZhNTYwM2UzMTZjZWI3NjdiOWJmMzIiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtMjk0OCIsImlhdCI6MTcxMDkwNDgzNSwiZXhwIjoxNzEwOTA4NDM1fQ.mrmF7kLCgtnolLbqT1w54lA7LkZdU6EPYMwEAYrH5BI
content-type: application/json

{
  "phoneNumber": "437-556-4035",
  "email": "svijayr007@gmail.com",
  "firstName": "Vijay",
  "lastName": "Pablo"
}

### New Admin Setup
POST http://localhost:3002/api/admin/setup
content-type: application/json

{
  "phoneNumber": "437-556-4035",
  "email": "svijayr007@gmail.com",
  "oneTimePassword": "nxtj1",
  "password": "Vijay@001"
}


### Admin Login
POST http://localhost:3002/api/admin/login
content-type: application/json

{
  "email": "svijayr007@gmail.com",
  "password": "Vijay@001"
}

### Admin Get All Users
GET http://localhost:3002/api/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWZhNTYyOGZjZDgxMGU4Mzk2ODQ0YjAiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtNDAzNSIsImlhdCI6MTcxMDkwNDk4MSwiZXhwIjoxNzEwOTkxMzgxfQ.9HB-vpU3SpDfApwiZnRJEoBLuFeOMVf1NSoMM18JN5o
content-type: application/json