### Create Admin User
POST http://localhost:3002/api/admin/sadmin/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWY0NjkwNjFmZjk5NGQ4YWFlMjYwOWIiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtMjk0OCIsImlhdCI6MTcxMDUxNzM0MCwiZXhwIjoxNzEwNTIwOTQwfQ.PupgTeHielJPIPHf9dF53mM2-pLtV_nt5WGLhusrz8Y
content-type: application/json

{
  "phoneNumber": "437-556-4035",
  "email": "svijayr007@gmail.com",
  "firstName": "Vijay",
  "lastName": "Pablo"
}

### New Admin Setup
POST http://localhost:3002/api/admin/setup
content-type: application/json

{
  "phoneNumber": "437-556-4035",
  "email": "svijayr007@gmail.com",
  "oneTimePassword": "n4oal",
  "password": "Vijay@001"
}


### Admin Login
POST http://localhost:3002/api/admin/login
content-type: application/json

{
  "email": "svijayr007@gmail.com",
  "password": "Vijay@001"
}

### Admin Get All Users
GET http://localhost:3002/api/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWY0NzJiMDVkNTlmZGIxZGJlZjhhMGYiLCJwaG9uZU51bWJlciI6IjQzNy01NTYtNDAzNSIsImlhdCI6MTcxMDUxOTE3NCwiZXhwIjoxNzEwNjA1NTc0fQ.xcnx-49hrx9HOqqc1TAhVMVcajygE3cv_9wR9rn-f80
content-type: application/json